service: inventoryService

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  role: ${file(../roleARN.yaml):roles.LabRole}
  environment:
    TABLE_NAME: ${self:service}-${opt:stage, 'dev'}

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /inventory
          method: any
          cors: true
      - http:
          path: /inventory/{product_id}
          method: any
          cors: true

resources:
  Resources:
    InventoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: product_id
            AttributeType: S
          - AttributeName: last_update
            AttributeType: S
          - AttributeName: product_name
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: product_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: product_name-index
            KeySchema:
              - AttributeName: product_name
                KeyType: HASH
              - AttributeName: tenant_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        LocalSecondaryIndexes:
          - IndexName: last_update-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: last_update
                KeyType: RANGE
            Projection:
              ProjectionType: ALL